spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sporty
    username: sporty
    password: sporty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled=true
    baseline-on-migrate=true
    locations=classpath:db/migration
server:
  port: 8080
